Myproject/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('api-auth/', include('rest_framework.urls')),
   
]

if settings.DEBUG:
    urlpatterns += [

        re_path(r'^media/(?P<path>.*)$', serve, 
                
                {'document_root': settings.MEDIA_ROOT,}),


    ]

myapp/urls.py
from rest_framework import routers
from django.urls import path, include
from myapp import views
from rest_framework import permissions
from drf_yasg.views import  get_schema_view
from drf_yasg import openapi
router = routers.DefaultRouter()
router.register(r'mlmodels',views.MlmodelViewSet,  basename='mlmodel')
router.register(r'users',views.UserViewSet,  basename='user')

schema_view = get_schema_view(
   openapi.Info(
      title="Creditcard Fraud Detection Model",
      default_version='1.0',
      description="Check the fraud in Credit card Transactions",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="aisshiva766@gmail.com"),
      license=openapi.License(name="BSD License"),
      
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)



urlpatterns =[

   path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   path('', include(router.urls)),
   path('api_route/',views.api_root),
   path('form/', views.get_mlmodel),
   path('predict/', views.predict),
   path('predict/<int:id>', views.predict),
   path('train/', views.train),
   path('thanks/', views.thanks),
    
    
    
]

myapp/models.py
from django.db import models

# Create your models here.
class Mlmodel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    Time = models.IntegerField(default=0)
    V1 = models.DecimalField(max_digits=65,decimal_places=16)
    V2 = models.DecimalField(max_digits=65,decimal_places=16)
    V3 = models.DecimalField(max_digits=65,decimal_places=16)
    V4 = models.DecimalField(max_digits=65,decimal_places=16)
    V5 = models.DecimalField(max_digits=65,decimal_places=16)
    V6 = models.DecimalField(max_digits=65,decimal_places=16)
    V7 = models.DecimalField(max_digits=65,decimal_places=16)
    V8 = models.DecimalField(max_digits=65,decimal_places=16)
    V9 = models.DecimalField(max_digits=65,decimal_places=16)
    V10 = models.DecimalField(max_digits=65,decimal_places=16)
    V11 = models.DecimalField(max_digits=65,decimal_places=16)
    V12 = models.DecimalField(max_digits=65,decimal_places=16)
    V13 = models.DecimalField(max_digits=65,decimal_places=16)
    V14 = models.DecimalField(max_digits=65,decimal_places=16)
    V15 = models.DecimalField(max_digits=65,decimal_places=16)
    V16 = models.DecimalField(max_digits=65,decimal_places=16)
    V17 = models.DecimalField(max_digits=65,decimal_places=16)
    V18 = models.DecimalField(max_digits=65,decimal_places=16)
    V19 = models.DecimalField(max_digits=65,decimal_places=16)
    V20 = models.DecimalField(max_digits=65,decimal_places=16)
    V21 = models.DecimalField(max_digits=65,decimal_places=16)
    V22 = models.DecimalField(max_digits=65,decimal_places=16)
    V23 = models.DecimalField(max_digits=65,decimal_places=16)
    V24 = models.DecimalField(max_digits=65,decimal_places=16)
    V25 = models.DecimalField(max_digits=65,decimal_places=16)
    V26 = models.DecimalField(max_digits=65,decimal_places=16)
    V27 = models.DecimalField(max_digits=65,decimal_places=16)
    V28 = models.DecimalField(max_digits=65,decimal_places=16)
    Amount = models.IntegerField(default=0)
    owner = models.ForeignKey('auth.User', related_name='mlmodels', on_delete=models.CASCADE)
    

    def __str__(self):
        return (str(self.owner) + str(self.created))
    class Meta:
        ordering = ['created']
   
   
    def save(self, *args, **kwargs):
        Time = kwargs.get('Time', 0)    
        V1 = kwargs.get('V1', 0)
        V2 = kwargs.get('V2', 0)
        V3 = kwargs.get('V3', 0)
        V4 = kwargs.get('V4', 0)
        V5 = kwargs.get('V5', 0)
        V6 = kwargs.get('V6', 0)
        V7 = kwargs.get('V7', 0)
        V8 = kwargs.get('V8', 0)
        V9 = kwargs.get('V9', 0)
        V10 = kwargs.get('V10', 0)
        V11 = kwargs.get('V11', 0)
        V12 = kwargs.get('V12', 0)
        V13 = kwargs.get('V13', 0)
        V14 = kwargs.get('V14', 0)
        V15 = kwargs.get('V15', 0)
        V16 = kwargs.get('V16', 0)
        V17 = kwargs.get('V17', 0)
        V18 = kwargs.get('V18', 0)
        V19 = kwargs.get('V19', 0)
        V20 = kwargs.get('V20', 0)
        V21 = kwargs.get('V21', 0)
        V22 = kwargs.get('V22', 0)
        V23 = kwargs.get('V23', 0)
        V24 = kwargs.get('V24', 0)
        V25 = kwargs.get('V25', 0)
        V26 = kwargs.get('V26', 0)
        V27 = kwargs.get('V27', 0)
        V28 = kwargs.get('V28', 0)
        Amount = kwargs.get('Amount', 0)
        owner = kwargs.get('owner', 0)
        super(Mlmodel, self).save(*args, **kwargs)
    

myapp/forms.py
from django.forms import ModelForm 
from .models import Mlmodel

class MlmodelForm(ModelForm):
    
    class Meta:
        model = Mlmodel
        fields = ['id','Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'owner']
       

myapp/views.py
"""
This module contains views for the Django application, including API endpoints and viewsets for handling Mlmodel and User objects.
It also includes functions for training a machine learning model, making predictions, and rendering forms.
Classes:
    MlmodelViewSet: A viewset for viewing and editing Mlmodel instances.
    UserViewSet: A viewset for viewing and editing User instances.
Functions:
    api_root(request, format=None): API root endpoint providing links to user and mlmodel lists.
    get_mlmodel(request, format=None): Handles GET and POST requests for the Mlmodel form.
    predict(request, format=None): Handles POST requests to make predictions using the latest Mlmodel instance.
    Train(request): Handles POST requests to train a machine learning model using a CSV file.
    thanks(request, format=None): Renders a thank you page after data is saved to the model.
"""
from rest_framework.response import Response
from .permissions import IsOwnerOrReadOnly
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework import permissions
from .serializers import MlmodelSerializer ,UserSerializer
from .models import Mlmodel
from rest_framework.decorators import api_view ,permission_classes
from rest_framework.reverse import reverse
from rest_framework import renderers
from rest_framework.decorators import action
from django.contrib.auth.models import User
from rest_framework.renderers import StaticHTMLRenderer
from django.http import HttpResponseRedirect, HttpResponse
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics  import roc_auc_score ,roc_curve, f1_score,precision_score,recall_score,accuracy_score
import matplotlib.pyplot as plt
from sklearn.metrics import PrecisionRecallDisplay
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from .forms import MlmodelForm
from rest_framework.permissions import IsAuthenticated
# Create  your views here.

@api_view(['GET', 'POST'])
@permission_classes(( ))
def api_root(request, format=None):
    
    try:
         return Response({
        'users':    reverse('user-list', request=request, format=format),
        'mlmodels': reverse('mlmodel-list', request=request, format=format),
          })      
    except Exception as e:
        return Response({"error": str(e)}, status=500)
    




class MlmodelViewSet(viewsets.ModelViewSet):
   
    queryset = Mlmodel.objects.all()
    serializer_class = MlmodelSerializer
    permission_classes = [permissions.IsAuthenticated,
                          IsOwnerOrReadOnly]  
    
    @action(detail=True, methods=['post','get'],renderer_classes=[renderers.StaticHTMLRenderer])  
    def perform_predict(self, request ,pk,**kwargs):
        try:
           
            mlmodel = Mlmodel.objects.get(pk=pk)
            serializer = MlmodelSerializer(mlmodel, context={'request': self.request})
            data = serializer.data
            data_list = list(data.values())
            data_list = data_list[1:-1]    
            data_list = np.array(data_list).reshape(1,-1)
            with open("model_rf.pkl","rb") as f:
                model = pickle.load(f)
                f.close()
            predict_class = model.predict(data_list)    
            context = {
            "data": predict_class,
              }              

            return render(self.request, 'predict.html', context=context)
        except Exception as e:
            return Response({"error": str(e)}, status=500)
    @action(detail=False, methods=['post','get'],renderer_classes=[renderers.StaticHTMLRenderer])  
    def navigate_form(self, request ,**kwargs):
        try:

            return HttpResponseRedirect('/thanks')
        except Exception as e:
            return Response({"error": str(e)}, status=500)

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer




@api_view(['GET', 'POST'])
@permission_classes(())
def get_mlmodel(request, format=None):
    if request.method == 'POST':
        form = MlmodelForm(request.POST)
        

        
        if form.is_valid():
            form.save()
        queryset = Mlmodel.objects.last()
        return HttpResponseRedirect('/thanks/')
        
    else:
        form = MlmodelForm()
        context = {
            "form": form,
            'users': reverse('user-list', request=request, format=format),
            'mlmodels': reverse('mlmodel-list', request=request, format=format),
        }              
        return render(request, 'mlmodel.html', context=context)


@api_view(['GET', 'POST'])
@permission_classes(())
def predict(request,format=None):
  try:
    
     
        mlmodel = Mlmodel.objects.last()
        serializer = MlmodelSerializer(mlmodel, context={'request': request})
        data = serializer.data
        data_list = list(data.values())
        data_list = data_list[1:-1]    
        data_list = np.array(data_list).reshape(1, -1)
        with open("model_rf.pkl", "rb") as f:
            model = pickle.load(f)
            f.close()
        predict_class = model.predict(data_list) 
        context = {
            "data": predict_class,
            'users': reverse('user-list', request=request, format=format),
            'mlmodels': reverse('mlmodel-list', request=request, format=format),
        }              
        return render(request, 'predict.html', context=context)
  except Exception as e:
        return Response({"error": str(e)}, status=500)





@api_view(['GET', 'POST'])
@permission_classes(())
def train(request):
 try:
    if request.method =="POST":   
       df = pd.read_csv("creditcard.csv")
       X =df[df.columns[:-1]][0:10000]
       y = df[df.columns[-1]][0:10000]
       scaler  = StandardScaler()
       scaler.fit_transform(X)
       X_scaled = scaler.transform(X)
       X_train,X_test,y_train,y_test = train_test_split(X_scaled, y,test_size=0.33,random_state=42)
     # cls = RandomForestClassifier() 
       with open("model_rf.pkl","rb") as f:
          cls = pickle.load(f)
          f.close() 
       cls.fit(X_train,y_train )
       y_pred = cls.predict(X_test)
       classificationreport = classification_report(y_test,y_pred)
       f1score = f1_score(y_test,y_pred)
       precisionscore =precision_score(y_test,y_pred)
       recallscore = recall_score(y_test,y_pred)
       accuracyscore = accuracy_score(y_test,y_pred)
       y_score = cls.predict_proba(X_test)
       y_score =y_score[:,1]
       rocaucscore= roc_auc_score(y_test,y_score)
      

       return(render(request,'train.html',{ "data": "Data trained",
                                            'classificationreport':classificationreport,
                                             'f1score':f1score,
                                              'precisionscore':precisionscore,
                                               'recallscore':recallscore,
                                               'accuracyscore':accuracyscore,
                                               'rocaucscore':rocaucscore,                                                             
                                            }))
    else:
        
        return(render(request,'train.html',{"data":"Data ready for training ",
                                            }))
 except Exception as e:
    return Response({"error": str(e)}, status=500)

@api_view(['GET', 'POST'])
@permission_classes(())
def thanks(request, format=None):
    
        try:
            return render(request, "mlmodel.html", {
                "data": "The data is saved to the model.",
                'users': reverse('user-list', request=request, format=format),
                'mlmodels': reverse('mlmodel-list', request=request, format=format),
            })
        except Exception as e:
            return Response({"error": str(e)}, status=500)

myapp/templates/mlmodel.html
{% extends "rest_framework/base.html" %}

{% load static %}   



    {% block bootstrap_theme %}
    <link rel="stylesheet" href="{% static 'myapp/css/bootstrap.css' %}" type="text/css">
    <style>
h1 {text-align: center;}
p {text-align: center;}
table {
  width: 100%;
}

    </style>       
    

    {% endblock %}
    
    

    

    {% block content %}
    <body  style="background-color: aqua;">
    
    

    <h1>Credit Card Fraud Detection</h1>
    <script src="{% static 'myapp/js/jquery.js' %}"></script>
    <script src="{% static 'myapp/js/popper.js' %}"></script>
    <script src="{% static 'myapp/js/bootstrap.js' %}"></script>

    <p>Check the list of Users  :<a href="{{users}}">{{users}}  </a></p>  
    <p>Check the list of Model instances  :<a href="{{mlmodels}}">{{mlmodels}}   </a>  </p>
        
<br>

    <form method="post" style="text-align: center;">
        {% csrf_token %}
        
    <div style="text-align: center;">

        <table style="background-color: green; border: brown; text-align: center;">  
        <tr> <td> <p>API Route</td>              </p>      <td>  <p> :<a href='\'>         API route to serve Base Models</a> </p></td></tr>
        <tr> <td><p>Model Input Form</td>            </p>   <td> <p> :<a href="\form">     Model Input form</a> </p></td></tr>
        <tr> <td> <p>Predict on the Input Data</td>    </p> <td>  <p>:<a href="\predict">  Predict on Last Input Model Form data</a> </p></td></tr>
        <tr> <td><p>Train the Model for Accuracy</td>   </p> <td> <p>:<a href="\train">    Train the Model </a> </p></td> </tr>
    </table>
  </div>
        {{data}}           
        <tr>
            <br>
            <b> Please enter the Value of </b> 
            <th><label for="id_Time">Time:</label></th>
            <br>
            <td>
        
              <input type="number" name="Time" value=" " required id="id_Time" >
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V1">V1:</label></th>
            <br>
            <td>
        
              <input type="number" name="V1" value="0.0000000000000000" step="1e-16" required id="id_V1">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V2">V2:</label></th>
            <br>
            <td>
        
              <input type="number" name="V2" value="0.0000000000000000" step="1e-16" required id="id_V2">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V3">V3:</label></th>
            <br>
            <td>
        
              <input type="number" name="V3" value="0.0000000000000000" step="1e-16" required id="id_V3">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V4">V4:</label></th>
            <br>
            <td>
        
              <input type="number" name="V4" value="0.0000000000000000" step="1e-16" required id="id_V4">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V5">V5:</label></th>
            <br>
            <td>
        
              <input type="number" name="V5" value="0.0000000000000000" step="1e-16" required id="id_V5">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V6">V6:</label></th>
            <br>
            <td>
        
              <input type="number" name="V6" value="0.0000000000000000" step="1e-16" required id="id_V6">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V7">V7:</label></th>
            <br>
            <td>
        
              <input type="number" name="V7" value="0.0000000000000000" step="1e-16" required id="id_V7">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V8">V8:</label></th>
            <br>
            <td>
        
              <input type="number" name="V8" value="0.0000000000000000" step="1e-16" required id="id_V8">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V9">V9:</label></th>
            <br>
            <td>
        
              <input type="number" name="V9" value="0.0000000000000000" step="1e-16" required id="id_V9">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V10">V10:</label></th>
            <br>
            <td>
        
              <input type="number" name="V10" value="0.0000000000000000" step="1e-16" required id="id_V10">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V11">V11:</label></th>
            <br>
            <td>
        
              <input type="number" name="V11" value="0.0000000000000000" step="1e-16" required id="id_V11">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V12">V12:</label></th>
            <br>
            <td>
        
              <input type="number" name="V12" value="0.0000000000000000" step="1e-16" required id="id_V12">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V13">V13:</label></th>
            <br>
            <td>
        
              <input type="number" name="V13" value="0.0000000000000000" step="1e-16" required id="id_V13">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V14">V14:</label></th>
            <br>
            <td>
        
              <input type="number" name="V14" value="0.0000000000000000" step="1e-16" required id="id_V14">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V15">V15:</label></th>
            <br>
            <td>
        
              <input type="number" name="V15" value="0.0000000000000000" step="1e-16" required id="id_V15">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V16">V16:</label></th>
            <br>
            <td>
        
              <input type="number" name="V16" value="0.0000000000000000" step="1e-16" required id="id_V16">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V17">V17:</label></th>
            <br>
            <td>
        
              <input type="number" name="V17" value="0.0000000000000000" step="1e-16" required id="id_V17">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V18">V18:</label></th>
            <br>
            <td>
        
              <input type="number" name="V18" value="0.0000000000000000" step="1e-16" required id="id_V18">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V19">V19:</label></th>
            <br>
            <td>
        
              <input type="number" name="V19" value="0.0000000000000000" step="1e-16" required id="id_V19">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V20">V20:</label></th>
            <br>
            <td>
        
              <input type="number" name="V20" value="0.0000000000000000" step="1e-16" required id="id_V20">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V21">V21:</label></th>
            <br>
            <td>
        
              <input type="number" name="V21" value="0.0000000000000000" step="1e-16" required id="id_V21">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V22">V22:</label></th>
            <br>
            <td>
        
              <input type="number" name="V22" value="0.0000000000000000" step="1e-16" required id="id_V22">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V23">V23:</label></th>
            <br>
            <td>
        
              <input type="number" name="V23" value="0.0000000000000000" step="1e-16" required id="id_V23">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V24">V24:</label></th>
            <br>
            <td>
        
              <input type="number" name="V24" value="0.0000000000000000" step="1e-16" required id="id_V24">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V25">V25:</label></th>
            <br>
            <td>
        
              <input type="number" name="V25" value="0.0000000000000000" step="1e-16" required id="id_V25">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V26">V26:</label></th>
            <br>
            <td>
        
              <input type="number" name="V26" value="0.0000000000000000" step="1e-16" required id="id_V26">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_V27">V27:</label></th>
            <br>
            <td>
        
              <input type="number" name="V27" value="0.0000000000000000" step="1e-16" required id="id_V27">
        
        
            </td>
          </tr>
        
          <tr>
            
            <br>
            <b> Please enter the Value of </b> 
            <th><label for="id_V28">V28:</label></th>
            <br>
            <td>
        
              <input type="number" name="V28" value="0.0000000000000000" step="1e-16" required id="id_V28">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_Amount">Amount:</label></th>
            <br>
            <td>
        
              <input type="number" name="Amount" value="0" required id="id_Amount">
        
        
            </td>
          </tr>
        
          <tr>
            <br>
            <b> Please enter the Value of </b> 
            
            <th><label for="id_owner">Owner:</label></th>
            <br>
            <td>
        
              <select name="owner" required id="id_owner">
          <option value="">---------</option>
        
          <option value="1" selected>admin</option>
        
        </select>
        
        
        
        
            </td>
          </tr>
        
        <br>
        <br> 
        <button type="submit" name="submit">Submit</button>
        <br>
         </form> 
   

  
    


</body>
{% endblock %}
</html>

myapp/templates/predict.html
{% extends "rest_framework/base.html" %}
{% load static %}   
      

{% block bootstrap_theme %}
<link rel="stylesheet" href="{% static 'myapp/css/bootstrap.css' %}" type="text/css">
<style>
    h1 {text-align: center;}
    p {text-align: center;}
    
    table {
  width: 100%;
}    
        </style>       
        
           
{% endblock %}
    


{% block content %}

<body style="background-color: aqua;text-align: center;">
<h1>Credit Card Fraud Detection</h1>
<p>The results of predictions </p>
<script src="{% static 'myapp/js/jquery.js' %}"></script>
<script src="{% static 'myapp/js/popper.js' %}"></script>
<script src="{% static 'myapp/js/bootstrap.js' %}"></script>

<p>Check the list of Users  :<a href="{{users}}">{{users}}  </a></p>  
<p>Check the list of Model instances  :<a href="{{mlmodels}}">{{mlmodels}}   </a>  </p>



<div style="text-align: center;">
<table style="background-color:green; border: brown;text-align: center;">  
    <tr> <td> <p>API Route</td>              </p>      <td>  <p> :<a href='\'>         API route to serve Base Models</a> </p></td></tr>
    <tr> <td><p>Model Input Form</td>            </p>   <td> <p> :<a href="\form">     Model Input form</a> </p></td></tr>
    <tr> <td> <p>Predict on the Input Data</td>    </p> <td>  <p>:<a href="\predict">  Predict on Last Input Model Form data</a> </p></td></tr>
    <tr> <td><p>Train the Model for Accuracy</td>   </p> <td> <p>:<a href="\train">    Train the Model </a> </p></td> </tr>
</table>
</div>
<br/>
<br/>

<textarea style="height: 321px; width:890px; background-color: beige;text-align: center;">
The results of Predictions according to the Classifier model
1 - The classifier has predicted a Fraud Transaction
0 - The classifer has Predicted a Non Fraud Transaction

The results of the Fraud Prediction  is     {{data}}
</textarea>
</body>

{% endblock %}  
    

myapp/templates/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>